import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My first Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header  className="flex w-full p-5 justify-between">
        {/* left */}
        <div className="flex space-x-4 items-center">
          <p>About</p>
          <p>Store</p>
        </div>

        {/* right */}
        <div className="flex space-x-4 items-center">
          <p>Gmail</p>
          <p>Images</p>

          {/* Icon */}

        </div>
      </header>
      
      {/* Body */}

      {/* Footer */}
    </div>
  )
}
