import Head from 'next/head';
import Avatar from './../components/Avatar.js';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My first Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header  className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          
          {/* Icon */}
          <Avatar url = "https://www.publicdomainpictures.net/pictures/290000/nahled/red-gerbera-daisy-close-up.jpg" />
        </div>
      </header>
      
      {/* Body */}

      {/* Footer */}
    </div>
  )
}
